apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app4
  name: app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app4
    spec:
      nodeSelector:
        agentpool: userpool
      containers:
      - image: amarbessalah/snat-app:v4
        name: snat-app
        resources: {}
status: {}
