apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app6
  name: app6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app6
    spec:
      nodeSelector:
        agentpool: agentpool
      containers:
      - image: amarbessalah/snat-app:v6
        name: snat-app
        resources: {}
status: {}
